server:
  port: 8081

spring:
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672
  cloud:
    stream:
      function:
        definition: feedSupplier
      bindings:
        feedSupplier-out-0:
          destination: feeds.v1.events.new-post
